version: '3'

services:

  motus-app:
    build: ./motus
    ports:
      - "3000:3000"
    restart: always

  loadbalancer:
    build: ./loadbalancer
    ports:
      - "8080:80"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    volumes:
      - ./redis/data:/data
    restart: always

  score-app:
    build: ./score
    ports:
      - "3001:3001"
    environment:
        - REDIS_URL=redis://redis:6379
    restart: always

  redis-auth:
    image: redis:latest
    ports:
      - "16380:6379"
    volumes:
      - ./redis-auth/data:/data
    restart: always

  auth-app:
    build: ./auth
    ports:
      - "3003:3003"
    environment:
        - REDIS_URL=redis://redis-auth:6379
    restart: always